export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG";
export const CHANGE_PLAY_LIST = "palyer/CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_SONG_INDEX = "paly/CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_PLAY_SEQUENCE = "player/CHANGE_PLAY_SEQUENCE";
export const CHANGE_LYRICS = "player/CHANGE_LYRICS";
export const CHANGE_LYRICS_INDEX = "player/CHANGE_LYRICS_INDEX";
